runtime: nodejs22

instance_class: F2

handlers:
  - url: /.*
    script: auto


env_variables:
  NODE_ENV: 'production'
  ORIGIN_URL: 'https://client-dot-boxwood-builder-429215-k7.ue.r.appspot.com'
  DB_USER: 'postgres'
  DB_PASS: '6/SKkhmas:9m\09o'
  DB_NAME: 'maps'
  DB_HOST: '/cloudsql/boxwood-builder-429215-k7:us-central1:atrakcje-dolnego-slaska-maps'

service_account: boxwood-builder-429215-k7@appspot.gserviceaccount.com
service: server
